name: Deploy to App Engine

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v1.2.1
        with:
          version: 5.17.2
          run_install: true
      - run: pnpm run format:check
      - run: pnpm run lint:check
      - run: pnpm test
      - run: pnpm run build
      - id: deploy
        uses: google-github-actions/deploy-appengine@v0.3.1
        with:
          credentials: ${{ secrets.GCP_SA_KEY }}
