name: Deploy to App Engine

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: yarn
      - run: yarn format:check
      - run: yarn lint:check
      - run: yarn test
      - run: yarn build
      - id: deploy
        uses: google-github-actions/deploy-appengine@v0.3.1
        with:
          credentials: ${{ secrets.GCP_SA_KEY }}
